# Generated by Django 3.1.7 on 2021-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=10)),
                ('tenant_id', models.CharField(max_length=10)),
                ('site_name', models.CharField(max_length=50)),
                ('configuration', models.CharField(choices=[('GXX', 'GXX'), ('GHX', 'GHX'), ('GHS', 'GHS'), ('OHS', 'OHS'), ('OHX', 'OHX'), ('OXX', 'OXX')], max_length=4)),
                ('cluster', models.CharField(max_length=50)),
                ('noc_operator', models.CharField(max_length=100)),
                ('fs', models.CharField(max_length=100)),
                ('fe', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Site Database',
                'verbose_name_plural': 'Sites Database',
            },
        ),
    ]
