# Generated by Django 3.1.7 on 2021-03-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DgRun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites_database',
            old_name='site_id',
            new_name='site',
        ),
    ]
