# Generated by Django 3.1.7 on 2021-03-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DgRun', '0002_auto_20210312_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites_database',
            new_name='SitesDatabase',
        ),
    ]
