# Generated by Django 3.1.7 on 2021-03-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DgRun', '0003_auto_20210312_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesdatabase',
            name='fs',
        ),
        migrations.RemoveField(
            model_name='sitesdatabase',
            name='noc_operator',
        ),
    ]
