# Generated by Django 3.1.7 on 2021-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DgRun', '0004_auto_20210312_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField()),
                ('zone', models.CharField(max_length=25)),
                ('LegacySiteID', models.CharField(max_length=25)),
                ('SiteName', models.CharField(max_length=50)),
                ('GeneratorRunDHM', models.CharField(max_length=10)),
                ('GeneratorRunMinutes', models.CharField(max_length=10)),
                ('CummulativeRunningDHM', models.CharField(max_length=10)),
                ('CummulativeRunningMinutes', models.CharField(max_length=10)),
                ('GeneratorStopMinutes', models.CharField(max_length=10)),
                ('GeneratorStopDHM', models.CharField(max_length=10)),
                ('CummulativeStopMinutes', models.CharField(max_length=10)),
                ('CummulativeStopDHM', models.CharField(max_length=10)),
                ('datasourcename', models.CharField(max_length=10)),
                ('HTT_TrialSite', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Relay Data',
                'verbose_name_plural': 'Relay Data',
            },
        ),
    ]
