# Generated by Django 3.1.7 on 2021-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DgRun', '0006_auto_20210312_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesdatabase',
            old_name='cluster',
            new_name='Cluster',
        ),
        migrations.RenameField(
            model_name='sitesdatabase',
            old_name='configuration',
            new_name='Configuration',
        ),
        migrations.RenameField(
            model_name='sitesdatabase',
            old_name='fe',
            new_name='FE',
        ),
        migrations.RenameField(
            model_name='sitesdatabase',
            old_name='site',
            new_name='LegacySiteID',
        ),
        migrations.RenameField(
            model_name='sitesdatabase',
            old_name='tenant_id',
            new_name='Site',
        ),
        migrations.RenameField(
            model_name='sitesdatabase',
            old_name='site_name',
            new_name='SiteName',
        ),
    ]
